### ISSUE TITLE
Support realtime visualisation of changes

### ISSUE THREAD

**Issue by mdelapenya** [ipeychev/weoutline#43]
If other user adds something to the whiteboard, then viewers must refresh the browser to be aware of new changes

**Comment by ipeychev** [comment]
Yes, Manu, this will be done, I'm waiting for the server of WeDeploy to send proper events and then we will have it :)

/cc @eduardolundgren

**Comment by mdelapenya** [comment]
That's awesome Mr Peychev! I'm looking forward to it!

**Comment by ipeychev** [comment]
Btw, you may play with it using a tablet (where it is supposed to be mostly used - with the mouse is not that comfortable, at least for me) and provide some feedback :)

**Comment by mdelapenya** [comment]
👏  👏  👏

**Comment by ipeychev** [comment]
:)
Will let you know when we deploy the server part. Then this will start to work like a charm!
